### ISSUE TITLE
Feature request - remove invasive window etc.

### ISSUE THREAD

**Issue by ashleedawg** [e-motiv/Webextension-Bookmarks-in-search-engines#1]
_<sup>(More of a feature request than an issue report... the link within the extension brought me here, and I figured I'd leave this instead of a poor review on such a new app.)</sup>_

I'm looking for an app that does _one_ thing only: identify in my Google search results which of the pages exist in my Firefox bookmarks, **silently and non-invasively** (like maybe with a "⭐" or "🦊".)  (Less importantly, I'd like to see an _enable/disable option_ to make choose whether to compare the url root (domain) of the search result to the **roots** of my bookmarks

This app seems close once I found and disabled "highlight keywords" but I don't see any way to get rid of the super-invasive window that pops up every time I search, so I'll uninstall and check back at some point.

**Comment by e-motiv** [comment]
Just a quick reply, because I am not currently focusing on this extension.

Silently and non-invasive: Kinda silly for most people, because it almost
always finds results for people with a lot of bookmarks (since one  of the
search types searches for not exact urls). But I can insert an option to
always minimize and then show some notifications on the minimize left-over
window. First part is quickly programmed and the second seems like a nice
feature anyway.

If you mean the roots of your domain, well that's probably not gonna
happen. That will take too much time and slow down firefox..It already
finds roots, I think, not sure, but not both ways in any case But that
already takes *seconds* of Firefox time! (For people with a lot of
bookmarks) (Of course this is also due to one ore more remaining Firefox
bugs that haven't been fixed for YEARS, that wants bookmarks to be
reorganized in the sql database (and they should!)...(So maybe then..,but
don't get your hopes up. Open source and mozilla development is stagnating
since several years..and a HUGE learning curve to start on (I tried!!)..and
Chrome has no good bookmarks.. 😥))

I'll come back to this whenever I focus on this again...(unless you
convince me otherwise 😅)

Mvg,
[image: Ruby Contact Card]
<http://www.e-motiv.net/Ruben%20Goethals%20-%20e-motiv.vcf> Ruben
<Ruben@e-motiv.net>    @   e-motiv <http://www.e-motiv.net>
[image: Ruby] <http://www.e-motiv.net>
+32  (0) 484  /  23 78 78

**Comment by e-motiv** [comment]
ashleedawg, especially for you I added a minimized version (result icons only) today.

I looked into root domain searching in bookmarks, but the webextension API does not allow it. Probably won't for years, seeing how slow firefox development is today (especially bookmars & webetension API).

You can see it in here in paramater url --> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/search#Parameters
